import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { twMerge } from 'tailwind-merge';
import Providers from './components/providers';
import ThemeSwitcher from './components/themeSwitcher/ThemeSwitcher';

const montserrat = Montserrat({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={ twMerge('bg-slate-200 dark:bg-slate-900', montserrat.className) }>
        <Providers>
          <header className='h-[40px]'>
            <ThemeSwitcher />
          </header>
          <main>
            {children}
          </main>
          <div id='portal' />
        </Providers>
      </body>
    </html>
  );
}
