import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/globals.css';
import { twMerge } from 'tailwind-merge';
import Providers from '../../components/providers';
import ThemeSwitcher from '../../components/themeSwitcher/ThemeSwitcher';

const montserrat = Montserrat({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      Layout
      { children }
    </div>
  );
}
